import type { ComponentType } from "react";

import {
  ButtonPreview,
  CardPreview,
  SpinnerPreview,
  StarRatingPreview,
} from "@/components/previews/items/basics";
import {
  ActivityFeedPreview,
  AvatarPreview,
  BadgePreview,
  BarChartPreview,
  CalendarViewPreview,
  DataTablePreview,
  DatePickerPreview,
  DonutChartPreview,
  KanbanBoardPreview,
  KpiCardPreview,
  LineChartPreview,
  SparklinePreview,
  TimelinePreview,
} from "@/components/previews/items/data";
import {
  BannerPreview,
  EmptyStatePreview,
  ErrorPagePreview,
  NotificationCenterPreview,
  ProgressBarPreview,
  PullToRefreshPreview,
  SkeletonPreview,
  SnackbarPreview,
  ToastPreview,
  TypingIndicatorPreview,
} from "@/components/previews/items/feedback";
import {
  ChatInputPreview,
  FormValidationPreview,
  LoginFormPreview,
  SearchBarPreview,
  SocialLoginPreview,
} from "@/components/previews/items/forms";
import {
  CheckboxPreview,
  ComboboxPreview,
  FileUploadPreview,
  FilterPanelPreview,
  InlineErrorPreview,
  MultiStepFormPreview,
  OtpInputPreview,
  PasswordInputPreview,
  RadioButtonPreview,
  SelectPreview,
  SliderPreview,
  TagInputPreview,
  TextFieldPreview,
  TextareaPreview,
  ToggleSwitchPreview,
} from "@/components/previews/items/inputs";
import {
  AccordionPreview,
  HamburgerMenuPreview,
  NavbarPreview,
  TabsPreview,
} from "@/components/previews/items/navigation";
import {
  BackToTopPreview,
  BottomNavigationPreview,
  BreadcrumbPreview,
  CarouselPreview,
  LoadMorePreview,
  PaginationPreview,
  ScrollspyPreview,
  SegmentedControlPreview,
  SidebarPreview,
  StepperPreview,
  StickyHeaderPreview,
  TableOfContentsPreview,
} from "@/components/previews/items/navigation-extra";
import {
  ModalPreview,
  PopoverPreview,
} from "@/components/previews/items/overlay";
import {
  AlertDialogPreview,
  BottomSheetPreview,
  CartDrawerPreview,
  CommandPalettePreview,
  ContextMenuPreview,
  DrawerPreview,
  DropdownMenuPreview,
  MegaMenuPreview,
  ProductTourPreview,
  TooltipPreview,
  UserMenuPreview,
} from "@/components/previews/items/overlay-extra";
import {
  FooterPreview,
  HeroSectionPreview,
  InfiniteScrollPreview,
  ProductCardPreview,
  SettingsPagePreview,
} from "@/components/previews/items/sections";
import {
  AnnouncementBarPreview,
  CheckoutFormPreview,
  ComparisonTablePreview,
  CtaSectionPreview,
  FaqPreview,
  FeatureSectionPreview,
  FloatingActionButtonPreview,
  IconButtonPreview,
  ImageGalleryPreview,
  LogoCloudPreview,
  MessageBubblePreview,
  NewsletterSignupPreview,
  OnboardingChecklistPreview,
  PricingTablePreview,
  ProfileHeaderPreview,
  ReviewCardPreview,
  RichMenuPreview,
  SplitButtonPreview,
  TestimonialsPreview,
} from "@/components/previews/items/sections-extra";

/**
 * slug → プレビューコンポーネントの対応表（全100件）。
 *
 * 全てServer Componentなのでクライアントバンドルは増えない。
 * 未登録のslugは getPreview() が null を返し、カード側は
 * 従来のカテゴリアイコン表示にフォールバックする。
 */
export const previewRegistry: Record<string, ComponentType> = {
  accordion: AccordionPreview,
  "activity-feed": ActivityFeedPreview,
  "alert-dialog": AlertDialogPreview,
  "announcement-bar": AnnouncementBarPreview,
  avatar: AvatarPreview,
  "back-to-top": BackToTopPreview,
  badge: BadgePreview,
  banner: BannerPreview,
  "bar-chart": BarChartPreview,
  "bottom-navigation": BottomNavigationPreview,
  "bottom-sheet": BottomSheetPreview,
  breadcrumb: BreadcrumbPreview,
  button: ButtonPreview,
  "calendar-view": CalendarViewPreview,
  card: CardPreview,
  carousel: CarouselPreview,
  "cart-drawer": CartDrawerPreview,
  "chat-input": ChatInputPreview,
  checkbox: CheckboxPreview,
  "checkout-form": CheckoutFormPreview,
  combobox: ComboboxPreview,
  "command-palette": CommandPalettePreview,
  "comparison-table": ComparisonTablePreview,
  "context-menu": ContextMenuPreview,
  "cta-section": CtaSectionPreview,
  "data-table": DataTablePreview,
  "date-picker": DatePickerPreview,
  "donut-chart": DonutChartPreview,
  drawer: DrawerPreview,
  "dropdown-menu": DropdownMenuPreview,
  "empty-state": EmptyStatePreview,
  "error-page": ErrorPagePreview,
  faq: FaqPreview,
  "feature-section": FeatureSectionPreview,
  "file-upload": FileUploadPreview,
  "filter-panel": FilterPanelPreview,
  "floating-action-button": FloatingActionButtonPreview,
  footer: FooterPreview,
  "form-validation": FormValidationPreview,
  "hamburger-menu": HamburgerMenuPreview,
  "hero-section": HeroSectionPreview,
  "icon-button": IconButtonPreview,
  "image-gallery": ImageGalleryPreview,
  "infinite-scroll": InfiniteScrollPreview,
  "inline-error": InlineErrorPreview,
  "kanban-board": KanbanBoardPreview,
  "kpi-card": KpiCardPreview,
  "line-chart": LineChartPreview,
  "load-more": LoadMorePreview,
  "login-form": LoginFormPreview,
  "logo-cloud": LogoCloudPreview,
  "mega-menu": MegaMenuPreview,
  "message-bubble": MessageBubblePreview,
  modal: ModalPreview,
  "multi-step-form": MultiStepFormPreview,
  navbar: NavbarPreview,
  "newsletter-signup": NewsletterSignupPreview,
  "notification-center": NotificationCenterPreview,
  "onboarding-checklist": OnboardingChecklistPreview,
  "otp-input": OtpInputPreview,
  pagination: PaginationPreview,
  "password-input": PasswordInputPreview,
  popover: PopoverPreview,
  "pricing-table": PricingTablePreview,
  "product-card": ProductCardPreview,
  "product-tour": ProductTourPreview,
  "profile-header": ProfileHeaderPreview,
  "progress-bar": ProgressBarPreview,
  "pull-to-refresh": PullToRefreshPreview,
  "radio-button": RadioButtonPreview,
  "review-card": ReviewCardPreview,
  "rich-menu": RichMenuPreview,
  scrollspy: ScrollspyPreview,
  "search-bar": SearchBarPreview,
  "segmented-control": SegmentedControlPreview,
  select: SelectPreview,
  "settings-page": SettingsPagePreview,
  sidebar: SidebarPreview,
  skeleton: SkeletonPreview,
  slider: SliderPreview,
  snackbar: SnackbarPreview,
  "social-login": SocialLoginPreview,
  sparkline: SparklinePreview,
  spinner: SpinnerPreview,
  "split-button": SplitButtonPreview,
  "star-rating": StarRatingPreview,
  stepper: StepperPreview,
  "sticky-header": StickyHeaderPreview,
  "table-of-contents": TableOfContentsPreview,
  tabs: TabsPreview,
  "tag-input": TagInputPreview,
  testimonials: TestimonialsPreview,
  "text-field": TextFieldPreview,
  textarea: TextareaPreview,
  timeline: TimelinePreview,
  toast: ToastPreview,
  "toggle-switch": ToggleSwitchPreview,
  tooltip: TooltipPreview,
  "typing-indicator": TypingIndicatorPreview,
  "user-menu": UserMenuPreview,
};

export function getPreview(slug: string): ComponentType | null {
  return previewRegistry[slug] ?? null;
}

export function hasPreview(slug: string): boolean {
  return slug in previewRegistry;
}
