import {
  Apple,
  AppWindow,
  ArrowRightLeft,
  BadgeCheck,
  Bell,
  Bot,
  CalendarDays,
  ChartLine,
  ChartNoAxesCombined,
  ChevronsRight,
  CircleHelp,
  CircleUserRound,
  ClipboardList,
  Columns3,
  Command,
  Compass,
  CreditCard,
  Footprints,
  Gauge,
  GitCommitVertical,
  GraduationCap,
  HeartPulse,
  Inbox,
  KeyRound,
  Landmark,
  Layers,
  LayoutDashboard,
  LayoutGrid,
  LoaderCircle,
  MessageCircle,
  MessageSquare,
  MousePointerClick,
  PanelBottom,
  PanelLeft,
  PanelRightOpen,
  PanelTop,
  Quote,
  RectangleEllipsis,
  Rocket,
  Search,
  Settings2,
  ShoppingBag,
  ShoppingCart,
  Smartphone,
  Sparkles,
  Store,
  Table2,
  Tags,
  TextCursorInput,
  TriangleAlert,
  UserRound,
  type LucideIcon,
} from "lucide-react";

const iconMap: Record<string, LucideIcon> = {
  Apple,
  AppWindow,
  ArrowRightLeft,
  BadgeCheck,
  Bell,
  Bot,
  CalendarDays,
  ChartLine,
  ChartNoAxesCombined,
  ChevronsRight,
  CircleHelp,
  CircleUserRound,
  ClipboardList,
  Columns3,
  Command,
  Compass,
  CreditCard,
  Footprints,
  Gauge,
  GitCommitVertical,
  GraduationCap,
  HeartPulse,
  Inbox,
  KeyRound,
  Landmark,
  Layers,
  LayoutDashboard,
  LayoutGrid,
  LoaderCircle,
  MessageCircle,
  MessageSquare,
  MousePointerClick,
  PanelBottom,
  PanelLeft,
  PanelRightOpen,
  PanelTop,
  Quote,
  RectangleEllipsis,
  Rocket,
  Search,
  Settings2,
  ShoppingBag,
  ShoppingCart,
  Smartphone,
  Sparkles,
  Store,
  Table2,
  Tags,
  TextCursorInput,
  TriangleAlert,
  UserRound,
};

export function DynamicIcon({
  name,
  className,
}: {
  name: string;
  className?: string;
}) {
  const Icon = iconMap[name] ?? LayoutGrid;
  return <Icon className={className} aria-hidden />;
}
